import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { parseCatalog, buildSummary } from "../lib/catalog.mjs";
import { buildExtensionEntries } from "../lib/extensions.mjs";
import { SCENARIO_DEFINITIONS, enrichEntriesWithScenarios, buildScenarioSummary, scenarioDefinition } from "../lib/scenarios.mjs";
import { CATEGORY_DATA_PROFILES } from "../lib/data-profiles.mjs";

const projectDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const markdown = await readFile(path.join(projectDir, "data", "source", "README.md"), "utf8");
const upstream = JSON.parse(await readFile(path.join(projectDir, "data", "source", "upstream.json"), "utf8"));
const agricultureExtension = JSON.parse(await readFile(path.join(projectDir, "data", "extensions", "agriculture.json"), "utf8"));
const relatedResources = JSON.parse(await readFile(path.join(projectDir, "data", "research", "related-resource-libraries.json"), "utf8"));
const generated = JSON.parse(await readFile(path.join(projectDir, "data", "generated", "apis.json"), "utf8"));
const generatedSummary = JSON.parse(await readFile(path.join(projectDir, "data", "generated", "summary.json"), "utf8"));
const browserBundle = await readFile(path.join(projectDir, "..", "..", "docs", "demos", "public-apis-intelligence", "data", "catalog-data.js"), "utf8");
const { categories, entries: parsedEntries } = parseCatalog(markdown);
const extensionEntries = buildExtensionEntries(agricultureExtension);
const allCategories = [...categories, "Agriculture"];
const entries = enrichEntriesWithScenarios([...parsedEntries, ...extensionEntries]);
const summary = buildSummary(entries, allCategories, upstream);
const scenarioSummary = buildScenarioSummary(entries);
summary.scenarioSummary = scenarioSummary;
summary.totals.scenarios = scenarioSummary.totalScenarios;

assert.ok(entries.length >= 1600, `Expected a full catalog, received ${entries.length}`);
assert.equal(categories.length, 51, "Upstream category count changed; review the mapping intentionally");
assert.equal(extensionEntries.length, 12, "The verified agriculture source set changed; review it intentionally");
assert.equal(allCategories.length, 52, "Combined catalog should include the agriculture extension category");
assert.equal(new Set(entries.map((entry) => entry.id)).size, entries.length, "Entry IDs must be unique");
assert.ok(entries.every((entry) => entry.group && entry.category), "Every API must have a group and category");
assert.ok(entries.every((entry) => entry.group !== "其他"), "Every upstream category must have an intentional capability-group mapping");
assert.ok(entries.every((entry) => entry.score >= 0 && entry.score <= 100), "Scores must stay in range");
assert.ok(SCENARIO_DEFINITIONS.length >= 200, "Detailed scenario taxonomy unexpectedly shrank");
assert.equal(Object.keys(CATEGORY_DATA_PROFILES).length, allCategories.length, "Every combined category needs a concrete data profile");
assert.ok(Object.values(CATEGORY_DATA_PROFILES).every((profile) => profile.objects.length >= 4 && profile.fields.length >= 4 && profile.inputs.length >= 2), "Data profiles must expose concrete objects, inputs and fields");
assert.ok(entries.every((entry) => entry.scenarios.length >= 1), "Every API must map to at least one scenario");
assert.ok(entries.flatMap((entry) => entry.scenarios).every((scenario) => scenarioDefinition(scenario.id)), "Every scenario match must resolve to a definition");
assert.ok(scenarioSummary.totalScenarios >= 100, "Expected a broad set of populated scenarios");
assert.ok(scenarioSummary.scenarios.every((scenario) => scenario.dataObjects.length && scenario.searchTerms.length && scenario.typicalInputs.length && scenario.exampleFields.length && scenario.question), "Every populated scenario must explain and index data objects, inputs, fields and a practical question");
assert.equal(scenarioSummary.dataCatalog.length, summary.totals.groups, "Data catalog must cover every capability group");
assert.equal(scenarioSummary.dataCatalog.flatMap((group) => group.categories).length, allCategories.length, "Data catalog must expose all categories");
assert.equal(summary.totals.upstreamApis, parsedEntries.length, "Upstream totals must remain separately traceable");
assert.equal(summary.totals.extensionApis, extensionEntries.length, "Extension totals must remain separately traceable");
assert.ok(extensionEntries.every((entry) => entry.officialDocs.startsWith("https://") && entry.verifiedAt && entry.coverage && entry.limitations), "Every agriculture extension needs official documentation and verification boundaries");
assert.ok(scenarioSummary.scenarios.filter((scenario) => scenario.category === "Agriculture" && !scenario.general).length >= 8, "Agriculture should expose detailed, populated scenarios");
assert.ok(scenarioSummary.specificApiCount >= Math.floor(entries.length * 0.65), "At least 65% of APIs should have a specific scenario match");
assert.deepEqual(generated, entries, "Generated APIs are stale; run npm run sync:offline");
assert.equal(generatedSummary.totals.apis, entries.length);
assert.equal(generatedSummary.totals.scenarios, scenarioSummary.totalScenarios);
assert.equal(generatedSummary.scenarioSummary.specificApiCount + generatedSummary.scenarioSummary.fallbackApiCount, entries.length);
assert.equal(summary.totals.apis, Object.values(summary.distributions.auth).reduce((a, b) => a + b, 0));
assert.equal(summary.totals.apis, Object.values(summary.distributions.cors).reduce((a, b) => a + b, 0));
assert.equal(summary.totals.apis, Object.values(summary.distributions.tier).reduce((a, b) => a + b, 0));
assert.ok(summary.totals.browserDirect > 0, "Expected browser-direct candidates");
assert.ok(browserBundle.startsWith("window.__PUBLIC_APIS_CATALOG__ = "), "Direct-open browser data bundle is missing");
const bundled = JSON.parse(browserBundle.slice(browserBundle.indexOf("{") , browserBundle.lastIndexOf(";")).trim());
assert.equal(bundled.apis.length, entries.length, "Browser data bundle must contain the full catalog");
assert.equal(bundled.summary.totals.apis, entries.length, "Browser summary must match the catalog");
assert.equal(bundled.summary.totals.scenarios, scenarioSummary.totalScenarios, "Browser bundle must contain scenario navigation data");
assert.equal(relatedResources.libraries.length, 15, "Related resource catalog should retain the reviewed source set");
assert.equal(new Set(relatedResources.libraries.map((library) => library.id)).size, relatedResources.libraries.length, "Related resource IDs must be unique");
assert.ok(relatedResources.libraries.every((library) => library.repository.startsWith("https://github.com/")), "Every related resource needs a GitHub source");
assert.ok(relatedResources.libraries.every((library) => library.layer && library.assetTypes.length && library.relationToPublicApis && library.recommendedSubproject && library.boundary), "Every related resource must explain its layer, relationship, next project and validation boundary");
assert.ok(relatedResources.libraries.filter((library) => library.priority === "P0").length >= 7, "The catalog should identify a focused first-priority research set");

console.log(`PASS: ${entries.length} APIs (${parsedEntries.length} upstream + ${extensionEntries.length} agriculture extensions), ${allCategories.length} categories, ${scenarioSummary.totalScenarios} populated scenarios, ${scenarioSummary.specificApiCount} specific matches, ${relatedResources.libraries.length} related resource libraries`);
