/**
 * @generated by scripts/architecture-sync.mjs — do not edit.
 *
 * Measured from the tree, so the map's numbers cannot drift from the code.
 * `UNCLAIMED` is what no module on the map covers: run the sync script, then
 * either give an existing module a wider pattern in coverage.json or add the
 * node the repo has been missing.
 */

export const MEASURED: Record<string, { count: number; loc: number }> = {
  'architecture-map': { count: 16, loc: 2570 },
  'gallery': { count: 2, loc: 366 },
  'governance': { count: 3, loc: 113 },
  'h3': { count: 24, loc: 1564 },
  'h3-demo': { count: 9, loc: 4829 },
  'moovie': { count: 4, loc: 774 },
  'moovie-lab': { count: 23, loc: 5750 },
  'moovie-report': { count: 2, loc: 961 },
  'pages-pipeline': { count: 1, loc: 54 },
  'proposals': { count: 2, loc: 64 },
  'template': { count: 2, loc: 70 },
  'zhulink': { count: 2, loc: 296 },
}

export const UNCLAIMED: string[] = []
